In [13]:
#Basic importations
import numpy as np
import tensorflow_datasets as tfds
import tensorflow_text as text
import tensorflow as tf


# This is mainly for deep understanding of paper Attention is all you need 
## Check it out here : https://arxiv.org/abs/1706.03762 .  
Basically is creating a transformer to be able to translate words from english to portuguese in this specific case.


In [14]:
#We use the data provided by Ted fundation in tensorflow_datasets
examples, metadata = tfds.load('ted_hrlr_translate/es_to_pt', with_info=True,
                               as_supervised=True)



train_examples, val_examples = examples['train'], examples['validation']

In [15]:
#we will call data a class to not have a random global variable 
class Data():
    def __init__(self):
        #alternitavely we can ask in innit what language we want to train
        i=0
        #WE WILL GET THE DATASET IN WORKING CONDITIONS EVERY LIST(TRAIN_EXMAPLES[I]) GIVES US A (EXAMPLE 1, EXAMPLE 2)
        pt=[]
        es=[]
        #WE NEED TO DECODE IT TO UTF-8 SO IT IS PRESENTABLE AND WE ONLY WANT THE NUMPY
        for es_example, pt_example in list(train_examples):
            pt.append((pt_example.numpy()).decode('utf-8'))
            es.append((es_example.numpy()).decode('utf-8'))
        self.pt=pt
        self.es=es
        #And with this we have or data


Now we need to think about input embedding .
Because obviously computers dont understand strings, we need some kind of input. We will build an embedding from zero
from tensorflow_text.tools.wordpiece_vocab import bert_vocab_from_dataset -> will help us generate a word for word construction
But for this case we need it to be object database so Data() is not useful in this case, although we will use it later


BertTokenizer is a type of embedding described in detail in https://arxiv.org/abs/1810.04805, we will not go in detail, we will assume its effectivness in embedding (as they describe is a bidirectional representation from unlabeled text )




In [16]:
from tensorflow_text.tools.wordpiece_vocab import bert_vocab_from_dataset as bert

In [17]:
#Datos=Data()
# in this case lets generate a vocabulary of 5000 words
# WE USE MAP AND LAMBDA MAP MAPS ONTO ARRAY AND SIMPLY LAMBDA ES,PT: ES IS SETTING FROM BOTH ES AND PT SETTING THE RESULT TO ES
# THE RESEVED TOKENS ARE SIMPLY START FINISH conditions (recall we need to start and finish the input and output)
es_vocab = bert.bert_vocab_from_dataset(train_examples.map(lambda es,pt:es),vocab_size =5000,reserved_tokens=["[PAD]", "[UNK]", "[START]", "[END]"])
pt_vocab = bert.bert_vocab_from_dataset(train_examples.map(lambda es,pt:pt),vocab_size =5000,reserved_tokens=["[PAD]", "[UNK]", "[START]", "[END]"])


KeyboardInterrupt: 

In [ ]:

def write_vocab_file(filepath, vocab):
    with open(filepath, 'w',encoding='utf-8') as f:
        for token in vocab:
              print(token, file=f)

In [ ]:
write_vocab_file('es_vocab.txt',es_vocab)
write_vocab_file('pt_vocab.txt',pt_vocab)



And with this we have already created a vocabulary. To  encapsulate everything we could put it in a class in this way.

In [8]:
class Vocabgen:
    def __init__(self,filename1,filename2,num):
        es_vocab = bert.bert_vocab_from_dataset(train_examples.map(lambda es,pt:es),vocab_size =num,reserved_tokens=["[PAD]", "[UNK]", "[START]", "[END]"])
        pt_vocab = bert.bert_vocab_from_dataset(train_examples.map(lambda es,pt:pt),vocab_size =num,reserved_tokens=["[PAD]", "[UNK]", "[START]", "[END]"])
        #WE CREATE THE VOCABS AND WE WRITE THEM
        write_vocab_file(filename1,es_vocab)
        write_vocab_file(filename2,pt_vocab)
        #We could make it even better so that given two languages we create the vocabs but is not necessary at the moment
        
    def write_vocab_file(filepath, vocab):
        with open(filepath, 'w',encoding='utf-8') as f:
            for token in vocab:
                  print(token, file=f)

In [11]:
Vocabgen('es_vocab.txt','pt_vocab.txt',5000)

Now we can easily create the tokenizers using tensorflow_text.BertTokenizer(atext, **kargs)

In [18]:
class Tokenizer:
    def __init__(self):
        #the tokenizer class will have tokens of class BertTokenizer as .pr .es 
        self.pt = text.BertTokenizer('pt_vocab.txt', **{})
        self.es =text.BertTokenizer('es_vocab.txt', **{})

def add_start_end(ragged): #this function has been copied from tensorflow  guide to subwords
        #will add the start and end
        
        reserved_tokens=["[PAD]", "[UNK]", "[START]", "[END]"]
        START = tf.argmax(tf.constant(reserved_tokens) == "[START]")
        END = tf.argmax(tf.constant(reserved_tokens) == "[END]")
        count = ragged.bounding_shape()[0]
        starts = tf.fill([count,1], START)
        ends = tf.fill([count,1], END)
        return tf.concat([starts, ragged, ends], axis=1)
        
#AND WE CREATE ANOTHER CLASS THAT CONTAINS OUR TOKENIZER TO TOKENIZE AND DE-TOKENIZE
class Embedding:
    Tokens=Tokenizer()
        #tokenize ---->
        #This returns an output of (batch,word,wordpiece)
        #What we mean is that we have -> I am good. output-> [ [ [I(values)] , [am(values)] , [good(values)]] ]
    
    def detokenize(self,detokenizedata):
        detokenizept=(Tokens.pt.detokenize(detokenizedata[1]))
        detokenizees=(Tokens.es.detokenize(detokenizedata[0]))
        
        detokenizees= tf.strings.reduce_join(detokenizees, separator=' ', axis=-1)
        detokenizept= tf.strings.reduce_join(detokenizept, separator=' ', axis=-1)
        merged=[]
        merged.append(detokenizees)
        merged.append(detokenizept)
        return merged
    def tokenize(self,tokenizedata):
        tokenizept=(Tokens.pt.tokenize(tokenizedata[1])).merge_dims(1,2)
        tokenizees=(Tokens.es.tokenize(tokenizedata[0])).merge_dims(1,2)
        #this part is for preperation for our purposes
        tokenizept=(add_start_end(tokenizept)).to_tensor()# we apply to tensor to make the output a normal tensor
        tokenizees=(add_start_end(tokenizees)).to_tensor()# we apply to tensor to make the output a normal tensor
        
        #THIS TO TENSOR WILL MAKE THAT ON TH OUTPUT WE GET A LOT OF PADDING but thats easily removable
        
        merged=[]
        merged.append(tokenizees)
        merged.append(tokenizept)
        return merged
    
    
    
    
    

In [19]:
Datos=Data()
Embed=Embedding()

To show the conversions lets do a simple example

In [21]:
test=[]
testes=[]
testpt=[]
testpt.append(Datos.pt[12])#WE INCLUDE TWO EXAMPLES SO WE CHECK VARIABILITY OF BATCH SIZE
testpt.append(Datos.pt[13])
testes.append(Datos.es[13])
testes.append(Datos.es[12])
print(Datos.pt[12])
test.append(testes)
test.append(testpt)
tokenizeddata=Embed.tokenize(test)
#We will try to detokenize to see if its working!
print(tokenizeddata)

print((Embed.detokenize(tokenizeddata)[1].numpy())[1].decode('utf-8')) #this goes to the pt detokenize data and decodes 
#it in a tensor
#then we are specifically getting the first text and decoding it  
print((Datos.pt[13]))
#ITS REALLY IMPORTAnt to decode de output, it will be coded in utf-8 to make it leggible we need to decode 
#AND as it can be seen we have a desired output only some random spaces that we do not need to bother about as differences
#IT IS ALSO INCLUDED THE START AND END WHICH IS EXACTLY WHAT WE NEED



`` eles não dizem : `` '' quero água quente nos chuveiros . ''
[<tf.Tensor: shape=(2, 23), dtype=int64, numpy=
array([[   2,  282,   16,   10,  281,   11,    3,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0],
       [   2,   38,   38,  197,  776,   14,   38,   38,    9,    9,  324,
         333,  442, 2805,  191,  200,   42, 1070, 2101,   16,    9,    9,
           3]], dtype=int64)>, <tf.Tensor: shape=(2, 24), dtype=int64, numpy=
array([[   2,   39,   39,  162,  117,  658,   28,   39,   39,    9,    9,
         264,  373, 1950,  133,   42,  523,  201,  557, 1674,   16,    9,
           9,    3],
       [   2,  282,   16,   10,  209,   11,    3,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0]], dtype=int64)>]
[START] obrigado . ( aplausos ) [END] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]
obriga

## Usage of class Embed
Embed has Embed.tokenizedata(data) ->(tokenizedspanish,tokenizedpt)as dtype= Tensor


Embed has Embed.detokenizedata(data) ->(detokenizedspanish,detokenizedpt) as dtype= Tensor


Be careful with detokenized as it should be decoded again!
For now they are only crated for the specific case of spanish and pt.

It will include de START AND END ALSO in both 

## Usage of class Data
Data() -> Data.pt ->(Data pt)


       -> Data.es ->(Data es) 


# ALL IS HEAVILY INFLUENCED BY https://www.tensorflow.org/text/guide/subwords_tokenizer?hl=es-419%C3%A7

As it is just a learning project

In [12]:
BATCH_SIZE=2
BUFFER_SIZE=20000
Embed=Embedding()
Tokens=Tokenizer()
def tokenize_pairs(es,pt):
    data2=[]
    data2.append(es)
    data2.append(pt)
    pt = Embed.tokenize(data2)[1]
    # Convert from ragged to dense, padding with zeros.
    es=Embed.tokenize(data2)[0]
    # Convert from ragged to dense, padding with zeros.
    return es,pt
def make_batches(ds):
    return (
      ds
      .cache()
      .shuffle(BUFFER_SIZE)
      .batch(BATCH_SIZE)
      .map(tokenize_pairs, num_parallel_calls=tf.data.AUTOTUNE)
      .prefetch(tf.data.AUTOTUNE))

examples, metadata = tfds.load('ted_hrlr_translate/pt_to_en', with_info=True,
                               as_supervised=True)


train_examples, val_examples = examples['train'], examples['validation']
train_batches=make_batches(train_examples)
for (batch, (inp, tar)) in enumerate(train_batches):
    print(inp)


tf.Tensor(
[[   2 1846   14   52 4816  274  564  480  188   59  501   51  306  441
  1659   42  274   58  306  424  736  653  413   57  653  274 1010   16
     3    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0]
 [   2   43 1446 3406  496   57 1400  301 2124  188 3087  852 1767  189
    39  198    1  189 1351  424 2017  501   59  501  801 2439  336   41
   653 1870  234  605 1107   15   20   42 1070  786 1797  501   53  396
   501 3084  188  265  605 1008  440   54  336 2269  274  258  356   16
     3]], shape=(2, 57), dtype=int64)
tf.Tensor(
[[   2   53  852 3187 2155   16    3    0    0    0    0    0    0    0
     0    0]
 [   2  191  413 4816  274   14  208   44  244  577  525   47  198  502
    32    3]], shape=(2, 16), dtype=int64)
tf.Tensor(
[[   2   53   39 3091 1008  231  208   53   40 3791  446   16    3    0
     0]
 [   2   84   41 2547  786  710 3161  227  229   39   58 4820  50

tf.Tensor(
[[   2   84   59  501   46 4135  501  197  413  369  878  292   16    3
     0    0    0    0    0    0    0    0    0    0    0    0]
 [   2   38   38   46  786   28   38   38    9    9   52 4816  274   47
  4357  198   39  215  212  653  244  682   16    9    9    3]], shape=(2, 26), dtype=int64)
tf.Tensor(
[[   2   43   14  188   44 3931   14  489   46  369  468 2396  198    3
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0]
 [   2   52 4816  274   84 1771   39  396  227  358  189   53   45  676
    54 2406   43   53 2978   54 2676   14 4252   58 2868  852  352  501
    53  198 3364  198   53 2978   53 2279   84   54  582  475 1070  577
   869   43   58  935  198 3084 1509  234   16    3]], shape=(2, 52), dtype=int64)
tf.Tensor(
[[   2   38   38   38   38    9    9  188  424  886  244   15  210  965
    15  396   59  501   39 

tf.Tensor(
[[   2  203  789  328   14  199  391   44  244  577  756   54  582  736
   444  926   52 4337  189 3820 4816  274   14  396  238  188  396  227
    51 3992  613   53  189   54  710  991 4543   16    3]
 [   2  242   41 4135 4818  369  238  208   54 3187  212  715 3508  415
   638   16    3    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0]], shape=(2, 39), dtype=int64)
tf.Tensor(
[[   2   51 3195  653  756  241  189   54  509  526  501  396  227   43
   886  920  502  188 1932  135   59  463  257   51  244  665   14  189
   227   53  396  212  653 2868   53 1070   52 4816  274  135   58 4820
   501   58  244  886  418   51  244  665 3838  188   39  852 3653 2987
    16    3]
 [   2   54  389  502   59  198  369   15  190  202   59  463   54  756
   518   14   40  358 4818  274   14   55 1307 1008  227   41  274 2406
    42  274 3023   16    3    0    0    0    0    0    0    0    0    0
     0    0    0    0    0 

tf.Tensor(
[[   2  192  241  727  501   53  189  188  878  501   44  244  577  756
    14 4252   52 4816  274   53  193  413 4816  274   39   44  244  577
   756   16    3    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0]
 [   2  211  736 1070  212  198  188   52  441  198  396  238   59  501
   367  188  211  435  356   39  212 2340   15   56  274 1070  810 2124
   422   14   43  211  736 1070  212  198  188   52  441  198   52 4816
   274  396  501   16    3]], shape=(2, 47), dtype=int64)
tf.Tensor(
[[   2 4252  202   47  198  502   14   60  274 1070   54  710  715 2406
   227  188   39 4801 2416   14   43   39  210  292  653 1400   54  241
   502  244  202  210   39 4801 2416  227   39   39  786  444 3380   53
  1130   84   53   54 3187  356 2331   46 4135  501  189   53  199 2269
  1089 1070   14   53 3317   16   41  358  424  736  479 1116   16    3]
 [   2   54  509  288  501  197  193  884 4818  274   53 2978   54  418
   526  238   39   51  244 

tf.Tensor(
[[   2  312   39  214  244   41  653  336 2155   39  274  190 3156  244
   616  690   39 1424 2161  188  235   53   51  244  665   48  274  878
   501   14  981 1070  188   47  356 2015  328  189  270 3407   59  501
   359 2124  396  227  238  188   44 1046  198  424 2017 4818 4816  274
   188 1919   16    3]
 [   2   54  274  664  501 1350   47 4603  203 1689  535   56 1070 4374
   198   14   54  418 2161  369   39  607  429 2124   42  274  665  635
    16    3    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0]], shape=(2, 60), dtype=int64)
tf.Tensor(
[[   2   43   39  227 1302 1115   41  274 1302  935  336   14  208 1211
    42  274  766   14   44  274  424   59  501  280   54 3187  356 2331
   198   39 1590  202   50  424  501 1947   39  204 1107  983 4816  274
    16    3]
 [   2   47 4603   84  208 2253  369  199 1590  336  501  197  209  301
    16    3    0    0    

tf.Tensor(
[[   2 4252   39  715  710  475  834  189 2124 3542  188  424  886  435
   369  188   57 4820   15  201   14  229 1453 1371   52 4816  274  652
    51  244  665  197 3201  336   14  652   59  463   41  274 2406   40
  4319  292   16    3]
 [   2   51  244  665   47  446  444  526  446   42  274  189   53  210
   480 2124  189   47 4603   39  595  446  640 1070   14   84   53 2296
  2124  209   16    3    0    0    0    0    0    0    0    0    0    0
     0    0    0    0]], shape=(2, 46), dtype=int64)
tf.Tensor(
[[   2  211 1422 4818  274 1070   51 3992  229  192  244   52 4816  274
   219 1009   57  274  577  921  653  244   16    3]
 [   2   43  747  501   42 2025  198  726  188   44  244  577  756   47
  4603   16    3    0    0    0    0    0    0    0]], shape=(2, 24), dtype=int64)
tf.Tensor(
[[   2   58 4801   28   45  389 3986  188  625  189   47  198  502  235
   415   54  389  198  627  878  292   43  189   39  921  279   44  389
   288   54  389  198  627  878  29

tf.Tensor(
[[   2  189   57  441  505  198  288   39 1070  413 4820  212  554   55
  2025  310 1446  878  198  288  210  234   42  274   54 1046  595   14
    43   55 2025 3808   51  244  665   52  756 2558  274  193 2340  878
   198  288   14  210  292  653 1400  235  415   39  701  212 4818 4816
   274   16 1504   16    3]
 [   2 4252  192  336   57  244 1551  654   42  274   53 1070 1839   14
   189  231 1504   16    3    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0]], shape=(2, 61), dtype=int64)
tf.Tensor(
[[   2 1351 1115  292   49 3932  849 1324   14   53   43  595  484 4356
   189   45  466  653  274 1070   53   54  877 2332  274 3742   14   54
   418  502 1070   51  244  665  188 1011   39  354   39 3730   53   41
  2547 3084 1509  737  574   43   41  653 3783 1070   78  204  715  292
   983 4816  274  188  189  

tf.Tensor(
[[   2   10  281   11    3    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0]
 [   2  199   47  198  502   44 1400  465  336   14   43   44 3175  756
    53  457 2253   51  244  665  927 2337  446   43  485   42  274  189
    53 1651   14  373  424  235   51  244  665  470   43  595  484 4132
    16    3]], shape=(2, 44), dtype=int64)
tf.Tensor(
[[   2   84  613   14   39  198 1475  188  193 1008 4379   58 4820  501
   396 3806   39   53  852  198  715 2628 1709  227   39  198   50  921
   653  418  321   53   45  274 1981  484   14   53 1364  198   43   53
   199 2413 3593   16    3]
 [   2   43 1070  219 1009 3105  188  420  234   14  208   55 1307 1008
   227   54  241  502  244  978   16    3    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0]], 

tf.Tensor(
[[   2   52 4816  274  489   39  198   56  241 3084 2412   14   52 4816
   274  489  199   39  198  391  504   14 4252  489  189   53   56  665
   595   84  192  336 3199   16    3]
 [   2   43   51 1070 2543   14   51 1070 2543  937  448  193  413 4816
   274   39   58 2886  292  653  435 2124 1420  925  276   39 3156  279
  1741  198   16    3    0    0    0]], shape=(2, 35), dtype=int64)
tf.Tensor(
[[   2   47  463  736 2688  501   59  463 1299 2124   40  935  595   41
  2547   59  463   50  921  653  244   46 1400 3952 1606  292  189   39
   927 2026 1336   39  274  210  480   16    3    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0]
 [   2   39 3688  459  415   40  244 1116   52 1303  418   43   39  198
     1   41 2547   39  198 1863  188   39 

tf.Tensor(
[[   2  628  202   59  463  193  595  346   41 3187 3820 4816   51 3992
    39  664 4802 2025  279  191  198  883  279  203   44  710 2969  198
    14  740   14  459  501 4816  389   43  459  501 4816  198   16    3]
 [   2 4252   39   56  244 1347  208   59  501 1999   14   52 2796 1999
    14   84   44 1400  301   16    3    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0]], shape=(2, 42), dtype=int64)
tf.Tensor(
[[   2   56  336  716 1606  310   39  274   54  582 3625  326   51  244
  2547  352   14  747   59  463   58  358  475  424 4818 4816  274  197
    47  198  292 4816  274  188   44 1046  435   41 2547   44  935 1008
   583  249 1264   28   52 4816  274 1771  249   53  198  548   14 4252
    58 2868  852  352  501  249   53  198   54  358  577  756  241   14
    43   52 4816  274 1771  202   53  198   46 4135  212  198   14 4252
    58 2868  852  352  501  202   39  198   51 3195  653  756  241   16
     3    

tf.Tensor(
[[   2  188  716  582 1070   55 2025  288  607   39  354  202  189  211
  3787  501  197  240   56  241 1744  878  198  288  217  359   16    3]
 [   2   43   55 1070 4565  238  135   55 1307   39  210  292  653 1400
    51  466  336 2969  188  211  756  546  388   39  251   32    3    0]], shape=(2, 28), dtype=int64)
tf.Tensor(
[[   2  226   53   41  653 4816  274   42  274 1630  605   51 1400  301
    44 1007 1070   41  274 3773  274  188 3115    3]
 [   2   47  198  502   84  607  257  241   51  244  665   42  274  189
   396  501   46  274  785   16    3    0    0    0]], shape=(2, 24), dtype=int64)
tf.Tensor(
[[   2  396  238   53   51 2221  786  441  292  480   42  274 1075   32
     3    0    0    0    0    0]
 [   2 4252   53  189   84   47  212  715 3287  878  292   14   84   39
   816  188 1426 1411   16    3]], shape=(2, 20), dtype=int64)
tf.Tensor(
[[   2  747  211  736 2797   41  274 2406  189   39  198  937   54  389
   526  501   44  244  577  756  202  189   

tf.Tensor(
[[   2   44 1400 2868 1048   41 4816  241   58  710 3271  198   39   44
   435 3943  227   43  886  786  411 1584   14    3    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0]
 [   2   58 1400 1464 2868   15  228   52  244 4802 1070 2330   39  189
    41  653 1870  358  501 3103  188  215 3496   15  927 3820 3187  852
  1070  424 4818 4816  274   16  203  214  244  257   14   53  198 2124
   786  710 3161  859  201  462  665  547  326  501  479  664  859   14
   189   60 4816  274   41 2547 4015  198   14  701  227 3187  212  653
   389  188   41 2547  786  641   43  701  227 3187  212  653  389  188
    51 4816  274 3927   53   54  582  475 2704   16    3]], shape=(

tf.Tensor(
[[   2   10  281   11  391  419  385 4603  364   59  501 1929   16    3
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0]
 [   2   41  653 1870   15  199   48  244 1010  198   14   48  274  852
    39  715  920  198   61 2019  653   57 1424  336 1302   14   43   57
   274  244   39  198  198  424  501   16    3]], shape=(2, 37), dtype=int64)
tf.Tensor(
[[   2   54  274  664  235   51 1400  854   16    3    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0]
 [   2 2124 3156  244   14   41 2547  388   39 1235 1480  336   14   39
    54  389  424 4818 4816  274 2124  189  210 2996  501  188  258   14
    53  292  653  933  202   40 

tf.Tensor(
[[   2 4252   46  369   53 1070 1839  198  548   16    3    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0]
 [   2   52  244  465  336   14  228  746  944   14   53  367  188   43
   475 1070  462 4818 4816  274  396  501  565  234  496   40  336  501
    16    3]], shape=(2, 30), dtype=int64)
tf.Tensor(
[[   2  193 1128  537  198   47 1479 3807 1237  280   39 3820  612  244
  2629   57 1046  998  249   39   50 2025   53  852  198  715 2628 1709
   501   53  211  595 1744  914   43   39  188  786  444  198 4816  274
    52  244  396  227  358   16    3    0    0    0    0    0    0    0
     0]
 [   2  188 2337  257   14   53  198 2710   60 4816  274  258   53   40
  3187  212 1008  234 1698   43   44 1046  653  435   54 1303  244 1413
   463   53 2888  501   14 4252   51 2416  238   39  927 3820 3187  852
  1070  424 4818 4816  274  605  198   43 2026 3383 4820  871  198   16
     3]], shape=(2, 57), dtype=int64)
tf.Tensor(
[

tf.Tensor(
[[   2   38   38  219   84   39   46  665  616  997  188   59  501  590
   188 1802  189   14   59  463  197 1461   14   46  369  194  198  635
    14 3433 2868   47  212 1009 3064  217  193  884 4818  274  203   40
   244  424  886  274  605  981  244 2315   43   41 4135 4818  435   39
   614   53  199 1070 2453  188   38   38    9    9   57 3076  301    9
     9    9    9   16    9    9    3]
 [   2   38   38   38   38    9    9  385 1364 1070  352  501   50  653
   336  191  198 1218 1070   39  396 1400  415  280 1225   15  559   32
     9    9    3    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0]], shape=(2, 77), dtype=int64)
tf.Tensor(
[[   2   38   38   59  501  927  244   55 2025  310  193 2340 1981   51
   244  665   44 1400  301  189  582  204  653 1709  227 3205  244   51
  3195  

tf.Tensor(
[[   2   39  541  358   14  242  204  653 1709  238   47  212 2023  277
    39  830  188   59  501   54  582  715  641 1269  576   16    3    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0]
 [   2  199   60  274  715 4820  396  501   44 3278  199  501 1500  336
   202   41  756  715  369   15  201   43   51 4097  227   39   54  444
   198 4816  274 1001   14   60  274  715 4820  396  501   59  463   54
   274 4818  244   16    3]], shape=(2, 47), dtype=int64)
tf.Tensor(
[[   2   44  244  577  305   42  274  228  502   41 2628 3287 2396 3015
    16    3]
 [   2   51 3992   53  852 3187 1149   16    3    0    0    0    0    0
     0    0]], shape=(2, 16), dtype=int64)
tf.Tensor(
[[   2  189  191  424 3382   14  229  652   32    3    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0  

tf.Tensor(
[[   2   53  198   44 2210  444   51  244  665  865   52  244  773 2447
    57 4816  274   53  198  746   43   39  198    1   16    3]
 [   2   60  274 1070 1318   15   60  389   42 2025  198  205  418   16
     3    0    0    0    0    0    0    0    0    0    0    0]], shape=(2, 26), dtype=int64)
tf.Tensor(
[[   2  209  501   16   43 1070  219 1009   39  188 3625 3805   39  198
    44  612  301 2969  198   42  274 2568   16    3]
 [   2   39  462 1581  424   53  199  715 1070 2977  369  690   16    3
     0    0    0    0    0    0    0    0    0    0]], shape=(2, 24), dtype=int64)
tf.Tensor(
[[   2 1526   39  627   14  391   41  653 4113   51  244  665   54  756
   328    3    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0]
 [  

tf.Tensor(
[[   2  188   44 3931   14  396  212  653  274  211  736 1070  212  198
    43  886  336  501  786  411   14  229  189  210  292  653 1400  981
  1364  466 4818  244   42  274  189 1318   39  214  244   47 1582 2340
   640   32    3    0    0    0    0    0    0    0    0    0    0    0]
 [   2   38   38   46  274  785   14   53 1070 4410   54  241  502  418
    39  927  577  756   41  274 2406  198  208   28   38   38    9    9
   396  238   59  501  359   52  241  301  460   14   43   41  653 1870
    15  199    9   51 1070 4818 3195 1324  389    9   16    9    9    3]], shape=(2, 56), dtype=int64)
tf.Tensor(
[[   2   58  227 1070 3815  188 2193   14   54  509  502  189   57 4816
   274    1   14  339   56 1709 2543   28  199  501   54  582  301 4818
  4816  274   16    3    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    

tf.Tensor(
[[   2   47  198  502   39  595  446  640 1070   14 2124  481  305   14
   229   52 4816  274  270 3407   52  509  653 2797   16    3]
 [   2  385 1364 1070  352  501  228   53 1070  878   44 1046  435   16
     3    0    0    0    0    0    0    0    0    0    0    0]], shape=(2, 26), dtype=int64)
tf.Tensor(
[[   2  219   44  274  424   39   54 3187  356 2969  701  501 3972  653
   244  605   56  336  595  664  135   39  215  212  653  244   53  227
  1197 1304 4818 4816  274  135    3    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0]
 [   2   38   38   54  509  502  189   55 1307 1008  227   59  501  189
  3491   52 2796  898   59  227 3933  225  199  501  786  710   39  504
    38   38    9    9   45  358 3626 2019  424    9    9    9    9   14
    43   46  369   15   53  198  188  242   53  198 1147   16    9    9
     3]], shape=(2, 57), dtype=int64)
tf.Tensor(
[[   2   43   47  198  502  396  878   59  50

tf.Tensor(
[[   2  416  878  577 1789  198  288  235   59  501  193  715 3187  616
   690  191 4802 2025 3808   52 4816  274  270 3407   59  463  685   39
   616 1463   14   53 1070   39  815   39   54  274 2015  501  503  208
   800  188 3368   14   53 1070   14  208   51 3992  198 1802  188 3087
   852 1767 2868   14   59  501  319   51 3992   14   51 3992  780  202
   211  736 2797 2760  336   41 2547   39   52 2868 1400 1186   16    3]
 [   2  203  789  328   39  863  189   84   40 2547   16    3    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0]], shape=(2, 84), dtype=int64)
tf.Tensor(
[[   2  211  736 2797  198  605  198   41  274 2406  198  189  262  621
    57 481

KeyboardInterrupt: 